[package]
name = "rddclient"
version = "0.6.0"
authors = ["Bret Curtis <psi29a@gmail.com>"]
description = "Fast, lightweight multi-provider Dynamic DNS updater supporting Cloudflare, DynDNS2, Namecheap, and more"
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/psi29a/rddclient"
edition = "2021"

[profile.release]
debug = false
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
env_logger = { version="0.11", default-features = false, features = ["humantime", "auto-color"] }
log = "0.4"
clap = { version = "4.6", default-features = false, features = ["std", "help", "derive"] }
minreq = { version = "3.0", default-features = false, features= ["json-using-serde", "https-rustls"] }
base64 = { version = "0.23", default-features = false, features = ["alloc", "std"] }
dirs = "6.0"
sha1 = { version = "0.10", default-features = false, features = ["std"] }
hex = { version = "0.4", default-features = false, features = ["alloc", "std"] }
urlencoding = { version = "2.1", default-features = false }
rand = { version = "0.10", default-features = false, features = ["std", "std_rng", "thread_rng"] }

[dev-dependencies]
cross = "0.2.5"
mockito = "1.7.1"
tempfile = "3.27"
