[package]
name = "cloudflareddns"
version = "0.2.0"
authors = ["Bret Curtis <psi29a@gmail.com>"]
description = "small, fast rust based cloudflare dns zone updator"
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/psi29a/cloudflareddns"
edition = "2021"

[profile.release]
debug = false
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"

[dependencies]
reqwest = { version = "0.12.7", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40.0", features = ["macros", "process", "rt", "rt-multi-thread"]}
config = "0.14.0"
env_logger = "0.11.5"
log = "0.4.22"
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }

[dev-dependencies]
cross = "0.2.5"
