name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-musl, x86_64-pc-windows-gnu]

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build for ${{ matrix.target }}
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --all --release --target=${{ matrix.target }}

      - name: Build for ${{ matrix.target }}
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo build --release --verbose

      - name: Copy build
        run: find target -type f -name 'cloudflare*' -exec mv -t . {} +

      - name: Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: cloudflareddns-${{ matrix.target }}
          compression-level: 9
          path: |
            LICENSE
            README.md
            cloudflare*

  macos-arm64-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Build
        run: cargo build --release --verbose
      - name: Copy build
        run: find target -type f -name 'cloudflareddns' -exec mv . {} +
      - name: Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: cloudflareddns-${{ runner.os }}-${{ runner.arch }}
          compression-level: 9
          path: |
            LICENSE
            README.md
            cloudflare*
