name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.7.3
    - name: Build
      run: cargo build --release --verbose
    - name: Artefacts
      uses: actions/upload-artifact@v4
      with:
        name: cloudflareddns
        path: |
          target/release/cloudflare
    - name: Run tests
      run: cargo test --verbose
